### ISSUE TITLE
Update manual to remove LGPT specifics

### ISSUE THREAD

**Issue by maks** [xiphonics/picoTracker#114]
Currently[ the manual states](https://github.com/democloid/picoTracker/blob/master/docs/MANUAL.md#importing-samples):
>It supports 8 or 16 Bit wav files, any sampling frequency, mono or stereo. 8bit samples are converted to 16bit at load time for compatibility with the engine (you can save space in storage but not in RAM, keep this in mind when choosing samples).

Which is actually not correct as freq above 44.1kHz are not supported. Its also likely that some schemes or big (little?) endian encodings are also not supported, so need to check the existing sample import handling code to see what exactly is supported and then update the manual accordingly.

Edit:
There are also likely other hold overs from it being the LGPT manual that dont apply to the picoTracker so I have renamed this issue to cover all that update work of going through the manual to remove LGPT specifics.

**Comment by democloid** [comment]
the readme says: 8 or 16bit samples up to 44.1kHz, mono or stereo :)

But the manual comes from another source

**Comment by maks** [comment]
@democloid good point! Really this should be a task to go through and scrub the manual for any LGPT docs that dont apply to the picotracker.

**Comment by maks** [comment]
done as of #219
