### ISSUE TITLE
Add warning if no SD card detected or faulty

### ISSUE THREAD

**Issue by h3o** [xiphonics/picoTracker#124]
On the initial screen (New/Load song) it would be useful to have a warning like "SD card missing or faulty" in case that the SD card cannot be accessed.

Subsequently, a warning should be displayed if creating a new song fails for some reason (for example because card is full, malfunctions or locks itself into write-protected mode).

Otherwise it may be confusing as New or Load commands cannot do anything without it (a newbie might forget inserting the SD card (as it happened to me :) 

Current behaviour: Without a SD card, pressing "Load" does not do anything, while "New" acts like it is allowing you to create a new song.

**Comment by Speccery** [comment]
I have started to work on this. As a first cut the no SD card status is detected by a new method in FileSystem object (method only implemented if PICOBUILD is defined).

Modified behaviour: message "**SD not present" shown as a path.

**Comment by maks** [comment]
@Speccery thats great! 🎉  Feel free to tag me as a reviewer once you have a PR ready or even if you want to get early feedback on a draft PR.
