### ISSUE TITLE
Making it easier to add new Instrument types

### ISSUE THREAD

**Issue by shockdesign** [xiphonics/picoTracker#126]
There are a few issues about adding new synths to picoTracker

- Amy https://github.com/democloid/picoTracker/issues/123
- Opal https://github.com/democloid/picoTracker/issues/102

Potentially a SID synth, etc and this issue - https://github.com/democloid/picoTracker/issues/36

I think we need a way to make Instruments easier to manage this.

Including on the Instrument screen a better way to switch what type of Instrument something is, etc... and how we define what options are available per Instrument.

i.e. Sample instruments have the sample name/file, volume, effect, etc?

Synth instruments would have specific variables as well..

Anyone with thoughts on this?

**Comment by maks** [comment]
I've been meaning to get back to working on instrument memory usage as I think its **very** bloated at the moment and can get significant savings in this area.
My back of envelope calcs say that ram usage per instrument excluding name & linked table should be less than 64 **bytes**! The current 8.5kB is just completely out there. Midi should be less than 16 bytes.

Given the above gutting the current implementation and fixing the instrument data structures should allow for large numbers of instruments, future synth instruments and still use less ram than the do currently.

To give some more context, I got this reply from one of the developers of Amy:

> re: RAM. We should figure this out "for real", and we have an issue to track it set up, but back of the envelope is at 120 oscs and reverb and chorus on, on an arm64 machine, we alloc a total of 117KB. the sizeof(synthinfo) is 437 bytes. in practice, it looks like each oscillator takes about 512 bytes of RAM
> FM voices take 9 oscillators
> So assume 4.5KB or so per FM voice. But also know there's some default stuff getting alloced no matter what. i'd like to get that # number down but it works fine on the chips we target (esp32s, arm cortex 0s/rpi, NXP/teensy)
> (also, everything is malloced at runtime with a fixed AMY_OSCS setting, it's not allocating dynamically as you add new voices. You'll have to set AMY_OSCS yourself lower if you want to save ram)
> 

So having *full* DX7 compatible FM instruments will only cost us 4.5KB per instrument, but just more basic 4-OP (like eg. Digitone) would only be around 2.5kB.

Note also that they are able to fit their whole engine **including** chorus & *reverb* fx into only 117kB!

**Comment by maks** [comment]
done as of  #219
