### ISSUE TITLE
Setup website for project using GitHub pages 

### ISSUE THREAD

**Issue by maks** [xiphonics/picoTracker#178]
Would be good to setup a GitHub pages website for the project. We already have man etc in markdown docs, so should be possible to setup Actions to build webpages from those docs on each commit to master branch as well.

**Comment by democloid** [comment]
What are you envisioning here? just a generic front end to the same data that is exposed on github? Not entirely sure that's necessary.

For an actual website about picoTracker I'm working on it myself.

**Comment by maks** [comment]
When we chatted about this in Discord I think the idea was to have a friendly format for the manual instead of pointing people at just the markdown file in the repo.

**Comment by maks** [comment]
obsolete.
