### ISSUE TITLE
Show flash usage

### ISSUE THREAD

**Issue by democloid** [xiphonics/picoTracker#185]
#136 had to be reverted due to issues with file browser, restore feature with more testing. Original commit: 58f6ab9785f84d38959f86c2c6192cd244ba34d9
Issue reported on #152

**Comment by maks** [comment]
I'll just repeat here what I commented on in #152:
@democloid yes all good. I'm not sure how its linked to the changes, I suspect maybe something to do with reading the filesizes from the sdcard, but I'll need to debug it properly. I'll try to get to it soon, as I find especially the filesize display if not the flash remaining an invaluable feature. I might try to tackle this as part of adding the FS in https://github.com/democloid/picoTracker/issues/171

**Comment by maks** [comment]
obsolete
