### ISSUE TITLE
Different font design and better readability

### ISSUE THREAD

**Issue by maks** [xiphonics/picoTracker#189]
The current font is very good, but possibly could be improved upon in terms of design aesthetic and readability.

I am working on some experiments in this area so this issue is to track and add visibility to that work. I'll post some potential designs as work progresses.

**Comment by RAWJUNGLE** [comment]
I think what's required here is line spacing.

https://github.com/democloid/picoTracker/pull/190

**Comment by maks** [comment]
done as of #219
