### ISSUE TITLE
Missing files in Browser 

### ISSUE THREAD

**Issue by RAWJUNGLE** [xiphonics/picoTracker#191]
I started rebuilding all the commits in picotracker behind you and noticed that there is a problem in this commit. 

When working with files, sometimes files are missing in directories. 
If I restart the project or reboot picotracker, the files reappear. Please pay attention.

https://github.com/democloid/picoTracker/commit/0608e018563fe4bb8ff37f2765c15afd37d4a660

**Comment by maks** [comment]
I've known about this for some time, I believe it was already discussed in the discord and I had added an issue for it, but seems I had missed doing that.

Feel free to submit a PR once you have a fix for this issue, otherwise I'll look into it once I get back to working on the file browser code.

**Comment by RAWJUNGLE** [comment]
> I've known about this for some time, I believe it was already discussed in the discord and I had added an issue for it, but seems I had missed doing that.
> 
> Feel free to submit a PR once you have a fix for this issue, otherwise I'll look into it once I get back to working on the file browser code.

I'm not good at writing code, as I've said this several times already. I am now doing a stable build that eliminates most of your commits.

**Comment by maks** [comment]
@RAWJUNGLE it's a liberally licenced open source project, you are free to do as you like, it's already been pointed out to you, if you are happy using older builds of the firmware, just do so.

**Comment by maks** [comment]
obsolete
