### ISSUE TITLE
SD card stop working , when load next file-list ,during previewing sample.

### ISSUE THREAD

**Issue by paasukusai** [xiphonics/picoTracker#196]
SD card stop working when load next file-list during previewing sample.
1.Open sample browser
2.Select 17th samples
3.Push Play button to do preview
4.Push Down button immediately
5.Preview glitches, next file list does not load (NG), SD card stop working.
  (sometimes preview goes well, but next file list dose not load, SD card not stop work.)
  
https://youtu.be/Bt3r6oqUYfA

samples in video
[sample_example.zip](https://github.com/user-attachments/files/15520767/sample_example.zip)

at build of 5/02 master
[Uploading 0502.zip…]()

**Comment by paasukusai** [comment]
For short samples, this does not occur very often, so access to the SD card may be conflicting.
If I don't scroll, the problem doesn't seem to occur.
It might be nice if scrolling could be disabled while previewing.

**Comment by maks** [comment]
Thanks for reporting this issue. I'm working on some changes to the sample file browser that should fix this.

**Comment by paasukusai** [comment]
[PagedImportSampleDialog.zip](https://github.com/user-attachments/files/16478342/PagedImportSampleDialog.zip)

I added countermeasure code.
Let me share it.

**Comment by maks** [comment]
Thank you for the contribution. 
I have actually refactored the file system and file browser code significantly to no longer require any dynamic memory allocations and have fixed this and many other issues with the filesystem code. I will push up my changes once I have finished testing them.

**Comment by maks** [comment]
done as of #219
