### ISSUE TITLE
Not supporting preview of long name samples. (Not intended?)

### ISSUE THREAD

**Issue by paasukusai** [xiphonics/picoTracker#214]
It seemed unintentional, so let me share this.

1.try to preview long name sample like this
  "VEC2 Cymbals HH Closed 01.wav"
2.can't preview

This code looks making issue.
*******************************************************************************
void picoTrackerPagedDir::getFileList(int startOffset,
                                      std::vector<FileListItem> *fileList) {

      // dirs get max len of 2 less than files becase they are shown surrounded
      // with "[]"
      current[indexEntry.type == DirIndex ? 23 : 25] =
          0; // truncate at 22 char length string

**Comment by maks** [comment]
Hi, thanks for filing this and other issues, but as I mentioned previously, the entire filesystem handling codebase has now been rewritten to not require any dynamic memory allocation, so it would be best to hold off on filing any issues for the file browser and file system parts of picoTracker until I get a chance to fully debug and test the new code and push it to this repo.

**Comment by maks** [comment]
done as of #219
