### ISSUE TITLE
Overclocking

### ISSUE THREAD

**Issue by paasukusai** [xiphonics/picoTracker#218]
Playback seems to break up when a lot of audio is played like attached project.
I would like to try overclocking, is there any other setting I should change besides SYS_CLK_KHZ,?

I know it could be a FLASH access speed issue, but if you have any advice it would be helpful.

[lgpt_FUKA.zip](https://github.com/user-attachments/files/17280850/lgpt_FUKA.zip)

**Comment by democloid** [comment]
picoTracker already runs overclocked, so I wouldn't recommend doing more than what it's doing right now, that said, yes, SYS_CLK is the one for the core clock.

In general picoTracker can run up to 5-6 tracks simultaneously pretty reliably, this is not the case with your project so I'll check if it's a sample format issue.

**Comment by paasukusai** [comment]
Thank you for the info!
I'll give up on overclocking for now.
As a spec upgrade, porting to pico2 would also be interesting.

Thank you.

**Comment by maks** [comment]
>Thank you for the info!
You're welcome.

>As a spec upgrade, porting to pico2 would also be interesting.
 
Yes it will be 👍🏻
