### ISSUE TITLE
Freezes after sustained use of sample browser preview

### ISSUE THREAD

**Issue by RAWJUNGLE** [xiphonics/picoTracker#66]
@democloid @maks 

I've noticed this problem when using picotracker for long periods of time. 
If you listen to samples in the browser for a long time, at one point the sound disappears. When you try to save and load the project, the device freezes. 

Still need a window to show how full the memory is in picotracker. It is very urgent.

I would add some more things to the song mode, it would display the bpm of the project and remove the name.
Also add an option to rename the project.

Also when working with samples there is a crunch in the sound (clicks). Can something be done about it?

**Comment by maks** [comment]
@RAWJUNGLE  Thanks for reporting these issues. 

Issues should be for a single issue only, so for this first time, I've created new separate issues for the clicking sound: #67 and feature request to change the song screen: #68 while there is an already existing issue covering displaying memory usage: #8 and renaming functionality: #64

I have also edited the title of this issue to match.
