### ISSUE TITLE
 Sound Glitches (clicks)

### ISSUE THREAD

**Issue by maks** [xiphonics/picoTracker#67]
Originally reported by @RAWJUNGLE : 

when working with samples there is a crunch in the sound (clicks). Can something be done about it?

**Comment by democloid** [comment]
This should be easy to reproduce if it happens consistently. @RAWJUNGLE, can you provide a project file showing the issue?

**Comment by gandaja** [comment]
[clickity.zip](https://github.com/democloid/picoTracker/files/14172904/clickity.zip)

**Comment by maks** [comment]
Thanks @gandaja is always very helpful to have examples demonstrating an issue. 👍🏻 
I'll try to have a look at that project soon.

**Comment by fpiesik** [comment]
I just filed a new issue to describe the problem better and suggest possible solutions: [https://github.com/xiphonics/picoTracker/issues/215](url)

**Comment by maks** [comment]
Closing as obsolete. Please file a new issue if this is still reproducible in latest release of v2.0 firmware.
