### ISSUE TITLE
Request for changes to song screen

### ISSUE THREAD

**Issue by maks** [xiphonics/picoTracker#68]
Originally requested by @RAWJUNGLE in a different issue:

I would add some more things to the song mode, it would display the bpm of the project and remove the name.

**Comment by democloid** [comment]
Checking this value is a screen away from the main song screen. Screen real estate is at a premium and don't see this as something that might need to be checked that often. I'm happy to hear counter arguments.

**Comment by maks** [comment]
Closing as obsolete.
